[project]
name = "kuntur-detector-api"
version = "1.0.0"
description = "API para gestiÃ³n de casos de UPC en Ecuador"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "uvicorn>=0.35.0",
    "pymongo>=4.6.0",
    "python-dotenv>=1.0.0",
]
